cmake_minimum_required(VERSION 3.10)
project(msr_cpp)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(CURL REQUIRED)
include_directories(${CURL_INCLUDE_DIR})
add_executable(msr main.cpp)
target_include_directories(msr PRIVATE include)
target_link_libraries(msr ${CURL_LIBRARIES})
if(CMAKE_SYSTEM_NAME MATCHES "Windows")
    target_link_libraries(msr ws2_32)
endif()